version: '3.6'
services:
  elasticsearch-monitoring:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-monitoring:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-monitoring:9200
      - LOGGING_QUIET=true
    depends_on:
      - elasticsearch-monitoring

volumes:
  elasticsearch-monitoring: