version: '3.6'
services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:latest
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    depends_on:
      - hub
  chrome:
    image: selenium/node-chrome:latest
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    depends_on:
      - hub

