name: ${ENVIRONMENT_NAME}
metricbeat.modules:
- module: system
  metricsets: ["cpu", "filesystem", "memory", "network", "process"]
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  enabled: true
  period: 10s
  hosts: ["unix:///var/run/docker.sock"]

- module: elasticsearch
  metricsets: ["node", "node_stats"]
  enabled: true
  period: 10s
  hosts: ["elasticsearch1:9200", "elasticsearch2:9200", "elasticsearch3:9200"]

- module: postgresql
  metricsets: ["activity", "bgwriter", "database"]
  enabled: true
  period: 10s
  hosts: ["postgres://db:5432"]
  username: lportal
  password: lportal

output.elasticsearch:
  hosts: ["elasticsearch-monitoring:9200"]

setup.dashboards.enabled: true
setup.kibana:
  host: "kibana"